from __future__ import annotations

def _default_pronunciation_lexicon() -> dict[str, str]:
    return {
        ".net": "dot net",
        "2fa": "tu ef ei",
        "abac": "a bak",
        "abstract factory": "abstract factori",
        "abstraction": "abstrakshon",
        "acceptance criteria": "acceptance criteria",
        "access token": "acces token",
        "acid": "asid",
        "acr": "ei si ar",
        "ad": "ei di",
        "adapter": "adapter",
        "adapter pattern": "adapter pattern",
        "adapters": "adapters",
        "adr": "ei di ar",
        "aggregate": "agregat",
        "aggregates": "agregats",
        "aggregation": "agregueishon",
        "agile": "ayail",
        "aks": "ei kei es",
        "alerting": "alertin",
        "alpha": "alfa",
        "android": "android",
        "anemic domain model": "anemic domain model",
        "angular": "angular",
        "ansible": "ansibol",
        "anti corruption layer": "anti corruption leier",
        "anti patterns": "anti patterns",
        "anti-pattern": "anti pattern",
        "api": "ei pi ai",
        "api gateway": "ei pi ai guéi tuei",
        "api gateway aws": "ei pi ai guéi tuei ei dobel iu es",
        "api key": "ei pi ai ki",
        "api management": "ei pi ai manash ment",
        "apis": "ei pi ais",
        "application": "apliqueishon",
        "application gateway": "apliqueishon guéi tuei",
        "applications": "apliqueishons",
        "architecture board": "arquitec shur bord",
        "architecture review": "arquitec shur riviu",
        "archimate": "arqui meit",
        "artifact": "artifact",
        "artifact repository": "artifact ripositori",
        "artifacts": "artifacts",
        "as-is": "as is",
        "assertion": "asershon",
        "ast": "ei es ti",
        "async": "eisink",
        "asynchronous": "eisincronous",
        "attack surface": "atak surface",
        "aurora": "aurora",
        "authentication": "autentiqueishon",
        "authorization": "authoraizeishon",
        "autoscaling": "autoskeilin",
        "availability": "availability",
        "availability zone": "availability zoun",
        "await": "aweit",
        "aws": "ei doble iu es",
        "azure": "ashur",
        "azure devops": "ashur devops",
        "azure functions": "ashur functions",
        "bdd": "bi di di",
        "backend": "bakend",
        "backend for frontend": "bakend for frontend",
        "backlog": "baklog",
        "backoff": "bakof",
        "backpressure": "bak presher",
        "backward compatibility": "bakward compatibility",
        "backward compatible api": "bakward compatible ei pi ai",
        "base": "beis",
        "bash": "bash",
        "batch": "bach",
        "bearer token": "berer token",
        "bean": "bin",
        "benchmarking": "benchmarkin",
        "beta": "beta",
        "bitbucket": "bit baket",
        "blackout": "blak aut",
        "blameless postmortem": "bleimles postmortem",
        "blast radius": "blast radius",
        "blue green deployment": "blu grin diplouiment",
        "bottleneck": "botelnek",
        "bounded context": "bounded context",
        "branch": "branch",
        "branches": "branches",
        "bridge": "brich",
        "bridge pattern": "brich pattern",
        "broker": "broker",
        "brownfield": "braunfild",
        "brownout": "braun aut",
        "bff": "bi ef ef",
        "build": "bild",
        "builder": "bilder",
        "builder pattern": "bilder pattern",
        "business continuity": "business continuity",
        "bulkhead": "bulkjed",
        "bpmn": "bi pi em en",
        "cache": "ka ché",
        "cache hit": "ka ché hit",
        "cache miss": "ka ché mis",
        "caching": "kaching",
        "callback": "kolbak",
        "canary deployment": "canari diplouiment",
        "capacity planning": "capacity planin",
        "cap theorem": "cap theorum",
        "casb": "cas bi",
        "cassandra": "casandra",
        "c#": "si sharp",
        "c sharp": "si sharp",
        "c++": "si plus plus",
        "cdc": "si di si",
        "cdn": "si di en",
        "certificates": "sertificates",
        "certificate": "sertificate",
        "change data capture": "cheinch deita captur",
        "chain of responsibility": "chein of risponsibility",
        "chaos engineering": "keios enyiniirin",
        "chatgpt": "chat yi pi ti",
        "checklist": "cheklist",
        "cherry pick": "cheri pik",
        "choreography": "coreografi",
        "cipher": "saifer",
        "cipher suite": "saifer suit",
        "ci": "si ai",
        "ci/cd": "si ai si di",
        "class diagram": "class daiagram",
        "clean architecture": "clin arquitectura",
        "cli": "si el ai",
        "clickhouse": "click jouse",
        "cloud": "claud",
        "cloudformation": "claud formation",
        "cloudfront": "claud front",
        "cloud run": "claud ran",
        "cloud sql": "claud es kiu el",
        "cloudwatch": "claud uoch",
        "cluster": "claster",
        "clusters": "clasters",
        "clustering": "clasterin",
        "closed source": "clousd sors",
        "cohesion": "cohishon",
        "cold start": "cold start",
        "command": "comand",
        "command pattern": "comand pattern",
        "commit": "comit",
        "compliance": "complaiens",
        "component": "component",
        "component diagram": "component daiagram",
        "components": "components",
        "composite key": "compozit ki",
        "composite pattern": "compozit pattern",
        "composer": "compouser",
        "composition": "composition",
        "compile time": "compail taim",
        "compiler": "compailer",
        "component diagram": "component daiagram",
        "compensating transaction": "compenseitin transaction",
        "compliance": "complaiens",
        "config server": "config server",
        "configmap": "config map",
        "connection pool": "conection pul",
        "consistency": "consistensi",
        "consumer": "consiumer",
        "consumer driven contract": "consiumer driven contract",
        "container": "container",
        "container diagram": "container daiagram",
        "containers": "containers",
        "context diagram": "context daiagram",
        "contract": "contract",
        "contract test": "contract test",
        "contract testing": "contract testing",
        "contract tests": "contract tests",
        "contracts": "contracts",
        "concurrency": "concurrency",
        "cors": "cors",
        "cost optimization": "cost optimization",
        "coupling": "kaplin",
        "cpu": "si pi iu",
        "c4 model": "si four model",
        "cqrs": "si kiu ar es",
        "cronjob": "cron yob",
        "cspm": "si es pi em",
        "csrf": "si es ar ef",
        "csv": "si es vi",
        "css": "si es es",
        "customervalue": "customervalue",
        "daemonset": "demon set",
        "dao": "di ei ou",
        "dashboard": "dashbord",
        "data bricks": "deita bricks",
        "data factory": "deita factori",
        "data lake": "deita leik",
        "data mart": "deita mart",
        "data warehouse": "deita uarejous",
        "database": "deita beis",
        "databases": "deita beises",
        "databricks": "deita bricks",
        "datadog": "deita dog",
        "dataplex": "deita plex",
        "dataproc": "deita proc",
        "dataset": "deitaset",
        "datasets": "deitasets",
        "datastream": "deita strim",
        "dead letter queue": "ded leter kiu",
        "deadlock": "dedlok",
        "decision record": "disishon record",
        "decorator": "decoreitor",
        "decorator pattern": "decoreitor pattern",
        "decryption": "dicryptshon",
        "definition of done": "definition of don",
        "definition of ready": "definition of redi",
        "deno": "deno",
        "denormalization": "dinormaleizeishon",
        "dependencies": "dependensis",
        "dependency": "dependensi",
        "dependency injection": "dependensi inyection",
        "dependency inversion": "dependensi inversion",
        "deploy": "dipluei",
        "deployment": "diplouiment",
        "deployment diagram": "diplouiment daiagram",
        "deprecation": "deprekeishon",
        "deserialization": "diserialeizeishon",
        "design pattern": "design pattern",
        "developer portal": "developer portal",
        "devops": "dev ops",
        "devsecops": "dev sec ops",
        "dhcp": "di eich si pi",
        "di container": "di container",
        "diagram": "daiagram",
        "dimension table": "dimension teibol",
        "dimensional modeling": "dimensional modeling",
        "disaster recovery": "disaster recovery",
        "distributed system": "distribiuted system",
        "distributed systems": "distribiuted systems",
        "distributed tracing": "distribiuted treisin",
        "distributed transaction": "distribiuted transaction",
        "djang o": "yango",
        "django": "yango",
        "dlp": "di el pi",
        "dns": "di en es",
        "docker": "doker",
        "docker compose": "doker compous",
        "dockerfile": "doker fail",
        "domain": "domain",
        "domain event": "domain event",
        "domain model": "domain model",
        "dotnet": "dot net",
        "downtime": "daun taim",
        "dry": "drai",
        "dto": "di ti ou",
        "dx": "di eks",
        "dynamodb": "dainamo di bi",
        "e2e": "i tu i",
        "ec2": "i si tu",
        "ecs": "i si es",
        "edge": "ech",
        "edge computing": "ech computing",
        "edr": "i di ar",
        "egress": "igres",
        "eks": "i keis",
        "elastic": "elastic",
        "elasticsearch": "elastic search",
        "electron": "electron",
        "elt": "i el ti",
        "embedding": "embedin",
        "embeddings": "embedins",
        "encryption": "encryptshon",
        "endpoint": "endpoint",
        "endpoints": "endpoints",
        "end of life": "end of laif",
        "end to end test": "end tu end test",
        "enterprise architecture": "enterprise arquitectura",
        "entra id": "entra ai di",
        "entities": "entitis",
        "entity": "entiti",
        "epic": "epic",
        "event bridge": "event brich",
        "event loop": "event lup",
        "event sourcing": "event sorsing",
        "event storming": "event stormin",
        "eventbridge": "event brich",
        "event hub": "event jab",
        "eventual consistency": "eventual consistensi",
        "exponential backoff": "eksponenshial bakof",
        "express": "express",
        "extensibility": "extensibility",
        "facade": "fasad",
        "facade pattern": "fasad pattern",
        "factory": "factori",
        "factory method": "factori method",
        "factory pattern": "factori pattern",
        "faas": "ef aas",
        "fake": "feik",
        "fallback": "folbak",
        "fan in": "fan in",
        "fan out": "fan aut",
        "fastapi": "fast api",
        "feature": "fichur",
        "feature flag": "fichur flag",
        "feature toggle": "fichur togol",
        "filebeat": "fail bit",
        "filtering": "filterin",
        "finops": "fin ops",
        "fixture": "fikscher",
        "flask": "flask",
        "fluent bit": "fluent bit",
        "fluentd": "fluent di",
        "flyweight pattern": "flaiweit pattern",
        "foreign key": "foren ki",
        "forward compatibility": "forward compatibility",
        "forward proxy": "forward proksi",
        "framework": "freimwork",
        "frontend": "fronend",
        "front door": "front dor",
        "ftp": "ef ti pi",
        "full join": "ful join",
        "full stack": "ful stak",
        "function as a service": "function as a servis",
        "functional requirement": "functional requirement",
        "functional requirements": "functional requirements",
        "garbage collection": "garbach colecshon",
        "garbage collector": "garbach colector",
        "gap analysis": "gap analisis",
        "gateway": "guéi tuei",
        "gcp": "yi si pi",
        "general availability": "yeneral availability",
        "git": "guit",
        "github": "guit jab",
        "gitlab": "guet lab",
        "go": "gou",
        "god object": "god object",
        "golden file": "golden fail",
        "golden path": "golden path",
        "golang": "gou lang",
        "google cloud": "gugol claud",
        "governance": "governans",
        "gpu": "yi pi iu",
        "grafana": "grafana",
        "graphql": "graf kiu el",
        "graceful degradation": "greisful degradation",
        "gradle": "greidel",
        "greenfield": "grinfild",
        "grpc": "yi ar pi si",
        "grooming": "grumin",
        "gui": "gui",
        "heap": "jip",
        "health check": "jelt chek",
        "heartbeat": "jartbit",
        "helm": "jelm",
        "hexagonal architecture": "jexagonal arquitectura",
        "hibernate": "jaibernet",
        "high availability": "jai availability",
        "high level design": "jai level design",
        "hsm": "eich es em",
        "hdd": "eich di di",
        "hotfix": "jot fix",
        "hot path": "jot path",
        "html": "eich ti em el",
        "http": "eich ti ti pi",
        "https": "eich ti ti pi es",
        "hybrid cloud": "jaibrid claud",
        "iam": "ai am",
        "iac": "ai ei si",
        "idempotency": "aidem potency",
        "idempotent": "aidem potent",
        "identity provider": "aidentiti provider",
        "idp": "ai di pi",
        "ids": "ai di es",
        "image": "imich",
        "images": "imiches",
        "imap": "ai map",
        "immutability": "imutability",
        "implementation": "implementeishon",
        "implementations": "implementeishons",
        "incident": "incident",
        "index": "index",
        "indexes": "indexes",
        "inference": "inferens",
        "influxdb": "inflaks di bi",
        "info sec": "infosec",
        "infosec": "infosec",
        "ingress": "ingres",
        "inheritance": "injeritans",
        "inner join": "iner join",
        "inner source": "iner sors",
        "input validation": "input valideishon",
        "insomnia": "insomnia",
        "infrastructure as code": "infrastructure as code",
        "integration test": "integréishon test",
        "integration tests": "integréishon tests",
        "interoperability": "interoparability",
        "interface": "interfeis",
        "interface segregation": "interfeis segregueishon",
        "interfaces": "interfeises",
        "interpreter": "interpreter",
        "interpreter pattern": "interpreter pattern",
        "inversion of control": "inversion of control",
        "ioc": "ai ou si",
        "ip": "ai pi",
        "ips": "ai pi es",
        "ipv4": "ai pi vi for",
        "ipv6": "ai pi vi siks",
        "ir": "ai ar",
        "ios": "ai ou es",
        "iterator pattern": "itereitor pattern",
        "jaeger": "yeiguer",
        "javascript": "yava scrit",
        "java": "yava",
        "jdbc": "yei di bi si",
        "jdeveloper": "yei developer",
        "jfrog": "yei frog",
        "jitter": "yiter",
        "job": "yob",
        "join": "join",
        "json": "yei son",
        "jwt": "yei doble tiu",
        "kanban": "kanban",
        "k8s": "keits",
        "key vault": "ki volt",
        "kibana": "kibana",
        "kms": "kei em es",
        "kpi": "kei pi ai",
        "kotlin": "kotlin",
        "kubectl": "kiu be control",
        "kubernetes": "kiu ber nets",
        "lambda": "lambda",
        "lambda function": "lambda function",
        "lan": "lan",
        "laravel": "laravel",
        "latency": "leitensi",
        "launch darkly": "lanch darkli",
        "layered architecture": "leierd arquitectura",
        "ldap": "el dap",
        "leader election": "lider election",
        "legacy code": "legasi code",
        "legacy system": "legasi system",
        "left join": "left join",
        "least privilege": "list privilege",
        "lexer": "lekser",
        "libraries": "laibreris",
        "library": "laibreri",
        "linter": "linter",
        "lint": "lint",
        "liskov substitution": "liskov substitushon",
        "livelock": "laivlok",
        "llm": "el el em",
        "load balancer": "loud balancer",
        "load test": "loud test",
        "logging": "login",
        "logic apps": "lochic aps",
        "log correlation": "log correlation",
        "logstash": "log stash",
        "long polling": "long polin",
        "loki": "loki",
        "low level design": "lou level design",
        "mariadb": "maria di bi",
        "masking": "maskin",
        "master data": "master deita",
        "materialized view": "materialized viu",
        "maven": "meiven",
        "maintainability": "meinteinability",
        "memento pattern": "memento pattern",
        "memcached": "mem cashed",
        "memory leak": "memori lik",
        "memorystore": "memori stor",
        "mermaid": "mermeid",
        "merge": "merch",
        "merge request": "merch riquest",
        "message broker": "message broker",
        "metadata": "metadeita",
        "metricbeat": "metric bit",
        "metrics": "metrics",
        "mfa": "em ef ei",
        "microservice": "maicroservis",
        "microservices": "maicroservises",
        "migration": "maigreishon",
        "migrations": "maigreishons",
        "milestone": "mailstoun",
        "minor version": "mainor version",
        "mock": "mok",
        "modular monolith": "modular monolith",
        "modularity": "modularity",
        "module": "modyul",
        "modules": "modyuls",
        "monitoring": "monitorin",
        "mongodb": "mongo di bi",
        "monolith": "monolith",
        "monorepo": "mono repo",
        "mvp": "em vi pi",
        "mutation testing": "miuteishon testing",
        "mutability": "mutability",
        "mysql": "mai es kiu el",
        "namespace": "neim espeis",
        "namespaces": "neim espeises",
        "nacl": "en a si el",
        "nat": "nat",
        "neo4j": "niou four yei",
        "nestjs": "nest yei es",
        "network policy": "network policy",
        "new relic": "niu relic",
        "next.js": "next yei es",
        "nextjs": "next yei es",
        "nexus": "nexus",
        "nfr": "en ef ar",
        "node": "nod",
        "node pool": "nod pul",
        "node.js": "nod yei es",
        "nodejs": "nod yei es",
        "non-functional requirement": "non functional requirement",
        "non-functional requirements": "non functional requirements",
        "normalization": "normaleizeishon",
        "nosql": "no es kiu el",
        "npm": "en pi em",
        "null object pattern": "nal object pattern",
        "nuxt": "nukst",
        "oauth": "ou oz",
        "object storage": "object storich",
        "observer": "observer",
        "observer pattern": "observer pattern",
        "observability": "observability",
        "oci": "ou si ai",
        "odbc": "ou di bi si",
        "offset pagination": "ofset pagineishon",
        "oidc": "ou ai di si",
        "okta": "okta",
        "on-call": "on col",
        "onion architecture": "anion arquitectura",
        "openai": "open ei ai",
        "openapi": "open api",
        "open closed principle": "open clous principle",
        "open source": "open sors",
        "opensearch": "open serch",
        "opentelemetry": "open telemetri",
        "oracle": "oracol",
        "oracle cloud": "oracol claud",
        "orchestration": "orquestreishon",
        "organization": "organization",
        "orm": "orm",
        "outbox pattern": "autbox pattern",
        "owasp": "ou uasp",
        "paas": "pi aas",
        "pacelc": "pa celc",
        "pagination": "pagineishon",
        "parallelism": "paralelism",
        "parser": "parser",
        "partition tolerance": "partition tolerance",
        "partitioning": "partitionin",
        "patching": "patchin",
        "patch version": "patch version",
        "payload": "peiload",
        "paved road": "peivd rod",
        "pdf": "pi di ef",
        "performance": "performance",
        "performance test": "performance test",
        "perl": "perl",
        "persistent volume": "persistent volium",
        "persistent volume claim": "persistent volium cleim",
        "pentest": "pen test",
        "penetration testing": "penetreishon testing",
        "pepper": "peper",
        "php": "pi eich pi",
        "pip": "pip",
        "pipeline": "paip lain",
        "pipelines": "paip lains",
        "platform engineering": "platform enyiniirin",
        "playbook": "pleibuk",
        "playground": "plei graund",
        "plugin": "pluguin",
        "plugins": "pluguins",
        "poc": "pi ou si",
        "pod": "pod",
        "pods": "pods",
        "poetry": "pouetry",
        "poka yoke": "poka yoke",
        "policy as code": "policy as code",
        "polyrepo": "poli repo",
        "polymorphism": "polimorfism",
        "pooling": "pulin",
        "pop3": "pop tri",
        "portability": "portability",
        "ports and adapters": "ports and adapters",
        "postman": "poustman",
        "postgres": "postgres",
        "postgresql": "post gres kiu el",
        "postmortem": "post mortem",
        "powershell": "power shell",
        "pre-commit": "pri comit",
        "preview": "priviu",
        "primary key": "praimari ki",
        "private cloud": "praivet claud",
        "private key": "praivet ki",
        "producer": "prodiuser",
        "profiling": "profilin",
        "prometheus": "promitius",
        "prompt": "promt",
        "prompts": "promts",
        "prototype pattern": "prototaip pattern",
        "proxy": "proksi",
        "proxy pattern": "proksi pattern",
        "public cloud": "public claud",
        "public key": "public ki",
        "pubsub": "pab sab",
        "pub/sub": "pub sab",
        "pull request": "pul riquest",
        "python": "pai ton",
        "qa": "kiu ei",
        "quality attribute": "kuoliti atribut",
        "queries": "kueris",
        "query": "kueri",
        "queue": "kiu",
        "quorum": "cuorum",
        "r": "ar",
        "rag": "rag",
        "rabbitmq": "rabit em kiu",
        "race condition": "reis condition",
        "ram": "ram",
        "rate limiting": "reit limi ting",
        "rbac": "ar bak",
        "rds": "ar di es",
        "react": "ri act",
        "reactjs": "ri act yei es",
        "real user monitoring": "rial iuser monitorin",
        "rebase": "ribéis",
        "redis": "redis",
        "redaction": "redakshon",
        "redshift": "red shift",
        "refresh token": "rifresh token",
        "region": "riyon",
        "regions": "riyons",
        "registry": "registry",
        "regression test": "rigreshon test",
        "reliability": "riliability",
        "release": "rilis",
        "release candidate": "rilis candidate",
        "release train": "rilis trein",
        "repository": "ripositori",
        "repository pattern": "ripositori pattern",
        "repositories": "ripositoris",
        "request": "riquest",
        "resource": "risors",
        "resources": "risorses",
        "response": "risponse",
        "rest": "rest",
        "restful": "restful",
        "retrospective": "retrospective",
        "retry": "ritrai",
        "retries": "ritraiz",
        "reverse proxy": "rivers proksi",
        "roadmap": "roudmap",
        "rollback": "rolbak",
        "rollback plan": "rolbak plan",
        "rolling deployment": "rolin diplouiment",
        "rom": "rom",
        "route 53": "raut fifti tri",
        "rpo": "ar pi ou",
        "rto": "ar ti ou",
        "ruby": "rubi",
        "runbook": "ranbuk",
        "runner": "raner",
        "runtime": "ran taim",
        "rust": "rast",
        "s3": "es tri",
        "saas": "saas",
        "safe": "seif",
        "saga": "saga",
        "salt": "solt",
        "saml": "samel",
        "sandbox": "sandboks",
        "sass": "sas",
        "scala": "scala",
        "scaffold": "skaffold",
        "scalability": "skeilability",
        "schema": "skima",
        "schema migration": "skima maigreishon",
        "scss": "es kass",
        "sdk": "es di kei",
        "sdlc": "es di el si",
        "secops": "sec ops",
        "secret": "sicret",
        "secret rotation": "sicret roteishon",
        "secrets management": "sicrets management",
        "security": "sicuriti",
        "security by design": "sicuriti bai design",
        "security group": "sicuriti grup",
        "self healing": "self jilin",
        "semver": "semver",
        "semantic versioning": "semantic versionin",
        "separation of concerns": "separeishon of concerns",
        "sequence diagram": "siquens daiagram",
        "serialization": "serialeizeishon",
        "serverless": "serverles",
        "service": "servis",
        "service bus": "servis bas",
        "service discovery": "servis discovery",
        "service registry": "servis registry",
        "service mesh": "servis mesh",
        "services": "servises",
        "session affinity": "seshon afiniti",
        "shared kernel": "sherd kernel",
        "sharding": "shardin",
        "shift left security": "shift left sicuriti",
        "singleton": "singuelton",
        "singleton pattern": "singuelton pattern",
        "siem": "si em",
        "sidecar": "saidecar",
        "single responsibility": "singol risponsibility",
        "skeleton": "skeleton",
        "sla": "es el ei",
        "sli": "es el ai",
        "slo": "es el ou",
        "smtp": "es em ti pi",
        "smoke test": "smouk test",
        "sns": "es en es",
        "soap": "soup",
        "soc": "sok",
        "software architect": "software arquitect",
        "software architecture": "software arquitectura",
        "software engineering": "software enyiniirin",
        "solid": "solid",
        "solution architect": "solution arquitect",
        "solutions architecture": "solutions arquitectura",
        "sonarqube": "sonar kiub",
        "sorting": "sortin",
        "source map": "sors map",
        "spaghetti code": "spagueti code",
        "spanner": "spaner",
        "specification pattern": "specificeishon pattern",
        "split brain": "split brein",
        "splunk": "splank",
        "spring": "spring",
        "spring boot": "spring but",
        "sprint": "sprint",
        "sql": "es kiu el",
        "sql server": "es kiu el server",
        "sqs": "es kiu es",
        "ssh": "es es eich",
        "ssl": "es es el",
        "ssd": "es es di",
        "sso": "es es ou",
        "stack": "stak",
        "standup": "standap",
        "star schema": "star skima",
        "state": "steit",
        "statefulset": "steitful set",
        "state pattern": "steit pattern",
        "step functions": "step functions",
        "sticky session": "stiki seshon",
        "stored procedure": "stored prosiyur",
        "stored procedures": "stored prosiyurs",
        "story": "stori",
        "strategy": "estrateyi",
        "strategy pattern": "estrateyi pattern",
        "strangler fig pattern": "strangler fig pattern",
        "stream processing": "strim procesin",
        "streaming": "strimin",
        "stress test": "estres test",
        "strong consistency": "strong consistensi",
        "stub": "stab",
        "subnet": "sabnet",
        "subtask": "sabtask",
        "surrogate key": "surrogueit ki",
        "swagger": "suager",
        "swift": "suift",
        "synthetic monitoring": "sinthetic monitorin",
        "synchronous": "sincronous",
        "synapse": "sinaps",
        "system design": "system design",
        "tag": "tag",
        "task": "task",
        "tdd": "ti di di",
        "tcp": "ti si pi",
        "technical debt": "tecnical det",
        "telemetry": "telemetri",
        "template": "templeit",
        "template method": "templeit method",
        "template pattern": "templeit pattern",
        "terraform": "terraform",
        "testability": "testability",
        "testing": "testing",
        "test coverage": "test coverage",
        "threat model": "zret model",
        "threat modeling": "zret modeling",
        "thread": "thred",
        "thread pool": "thred pul",
        "thread safety": "thred seifti",
        "throttling": "zrotlin",
        "throughput": "zruput",
        "timeout": "taim aut",
        "tls": "ti el es",
        "token": "token",
        "tokenization": "tokenaizeishon",
        "tokenizer": "tokenaizer",
        "tokens": "tokens",
        "togaf": "tougaf",
        "toml": "tomel",
        "topic": "topic",
        "to-be": "tu bi",
        "trace id": "treis ai di",
        "tracing": "treisin",
        "trade-off": "treid of",
        "trade-offs": "treid ofs",
        "transaction": "transaction",
        "transactions": "transactions",
        "tree shaking": "tri sheikin",
        "trigger": "trigger",
        "ts": "ti es",
        "tsv": "ti es vi",
        "tsx": "ti es eks",
        "typescript": "tai p scrit",
        "uat": "iu ei ti",
        "udp": "iu di pi",
        "ui": "iu ai",
        "uml": "iu em el",
        "unit of work": "iunit of uork",
        "unit test": "iunit test",
        "unit tests": "iunit tests",
        "unique constraint": "iunik constraint",
        "uptime": "ap taim",
        "uaf": "iu ei ef",
        "url rewriting": "iu ar el riraitin",
        "user story": "iuser stori",
        "ux": "iu eks",
        "vault": "volt",
        "vagrant": "veigrant",
        "value object": "valiu object",
        "vanity url": "vaniti iu ar el",
        "versioning": "versionin",
        "vertical scaling": "vertical skeilin",
        "view": "viu",
        "virtual machine": "virtual machin",
        "visitor": "visitor",
        "visitor pattern": "visitor pattern",
        "vm": "vi em",
        "vo": "vi ou",
        "vpc": "vi pi si",
        "vpn": "vi pi en",
        "vscode": "vi es code",
        "vue": "viu",
        "vuejs": "viu yei es",
        "vulnerability": "valnerability",
        "vulnerabilities": "valnerabilities",
        "waf": "uaf",
        "wan": "uan",
        "warmup": "uormap",
        "watchdog": "uoch dog",
        "webhook": "uebjuk",
        "webhooks": "uebjuks",
        "websocket": "ueb soket",
        "websockets": "ueb sokets",
        "workflow": "uorkflou",
        "wrapper": "wrapper",
        "wrappers": "wrappers",
        "wsdl": "doble u es di el",
        "wlan": "doble u lan",
        "wsl": "doble u es el",
        "xdr": "eks di ar",
        "x-ray": "eks rei",
        "xcode": "eks code",
        "xml": "eks em el",
        "xquery": "eks kueri",
        "xpath": "eks path",
        "xsd": "eks es di",
        "xss": "eks es es",
        "yaml": "yamel",
        "yagni": "yagni",
        "yarn": "yarn",
        "zachman": "sakman",
        "zero trust": "ziro trast",
        "zipkin": "zipkin",
        "zsh": "zi shell",
    }



def _default_spanish_accent_lexicon() -> dict[str, str]:
    return {
        "ademas": "además",
        "analitica": "analítica",
        "aplicacion": "aplicación",
        "aplicaciones": "aplicaciones",
        "arquitectonica": "arquitectónica",
        "autenticacion": "autenticación",
        "automatica": "automática",
        "automaticamente": "automáticamente",
        "capitulo": "capítulo",
        "caracter": "carácter",
        "codigo": "código",
        "conexion": "conexión",
        "configuracion": "configuración",
        "critica": "crítica",
        "critico": "crítico",
        "despues": "después",
        "diagnostico": "diagnóstico",
        "dialogo": "diálogo",
        "ejecucion": "ejecución",
        "especifica": "específica",
        "facil": "fácil",
        "foneticamente": "fonéticamente",
        "generacion": "generación",
        "informacion": "información",
        "ingles": "inglés",
        "integracion": "integración",
        "logica": "lógica",
        "mas": "más",
        "metricas": "métricas",
        "musica": "música",
        "numero": "número",
        "numeros": "números",
        "operacion": "operación",
        "optimizacion": "optimización",
        "pagina": "página",
        "parrafo": "párrafo",
        "parrafos": "párrafos",
        "podria": "podría",
        "produccion": "producción",
        "pronunciacion": "pronunciación",
        "puntuacion": "puntuación",
        "rapida": "rápida",
        "rapido": "rápido",
        "seccion": "sección",
        "segun": "según",
        "sintesis": "síntesis",
        "solucion": "solución",
        "tecnica": "técnica",
        "tecnico": "técnico",
        "tecnicos": "técnicos",
        "tecnologia": "tecnología",
        "termino": "término",
        "terminos": "términos",
        "todavia": "todavía",
        "transcripcion": "transcripción",
        "transicion": "transición",
        "ultima": "última",
        "ultimo": "último",
        "util": "útil",
        "validacion": "validación",
        "version": "versión",
        "vocalizacion": "vocalización",
    }
